### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'bndbox'

### ISSUE THREAD

**Issue by yannick3751** [weecology/NeonTreeEvaluation_python#7]
I used zenodo_get 4770593 to get the updated annotations

import pandas as pd
from src.eval import evaluate_image_crowns

submission = pd.read_csv("/content/submission.csv")
df = submission[submission.plot_name.isin(["DSNY_025_2018"])]

#Compute total recall and precision for the overlap data
results = evaluate_image_crowns(df = df,project = True, show=False)
results

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-4-3736f35bc1d3>](https://localhost:8080/#) in <cell line: 10>()
      8 
      9 #Compute total recall and precision for the overlap data
---> 10 results = evaluate_image_crowns(df = df,project = True, show=False)
     11 results

4 frames
[/content/NeonTreeEvaluation_python/src/eval.py](https://localhost:8080/#) in evaluate_image_crowns(path, df, shp, project, show, iou_threshold)
     36     results = [ ]
     37     for name, group in df.groupby("plot_name"):
---> 38         result = image_crowns(df=group, project=project, show=show)
     39         results.append(result)
     40 

[/content/NeonTreeEvaluation_python/src/image_crowns.py](https://localhost:8080/#) in image_crowns(df, project, show)
     23         plot_name = plot_names[0]
     24 
---> 25     ground_truth = get_data.load_ground_truth(plot_name)
     26     df = project_boxes(df, transform = project)
     27 

[/content/NeonTreeEvaluation_python/src/get_data.py](https://localhost:8080/#) in load_ground_truth(plot_name)
     49     """Load annotation and return projected data"""
     50     xml_path = get_data.find_path(plot_name, "annotations")
---> 51     ground_truth = xml_parse(xml_path)
     52 
     53     #convert to geopandas

[/content/NeonTreeEvaluation_python/src/get_data.py](https://localhost:8080/#) in xml_parse(path)
     37 
     38     df = pdx.read_xml(path, ["annotation","object"])
---> 39     xmin = df.bndbox.apply(lambda x: x["xmin"])
     40     xmax = df.bndbox.apply(lambda x: x["xmax"])
     41     ymin = df.bndbox.apply(lambda x: x["ymin"])

[/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py](https://localhost:8080/#) in __getattr__(self, name)
   5987         ):
   5988             return self[name]
-> 5989         return object.__getattribute__(self, name)
   5990 
   5991     def __setattr__(self, name: str, value) -> None:

AttributeError: 'DataFrame' object has no attribute 'bndbox'

This is the used submission file
[submission.csv](https://github.com/user-attachments/files/16288344/submission.csv)

**Comment by bw4sz** [comment]
Hey @yannick3751 , this never really came to completion compared to https://github.com/weecology/NeonTreeEvaluation and https://github.com/weecology/NeonTreeEvaluation_package. I'm going to add a deprecation notice to this readme. But, let's find a way to get you the information you need. If you can use R, the R package works fine. If not, I am happy to run scores for you.
